# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa8bd7b8d65ef345ed95a92f92f3806c4397c7e25c827eedda48dc0204efa09c50a9b74d30dd15b158dc090f78c774d622213c234cf76e87392df0d03eac0e1

test:
  secret_key_base: c975caa815df2dcaf1ebcabe966da1b827575d0ab89a20872816024e640da5ad68eff10d07801e398c1a5099a08f72010dddca870b155a24fe48fca28d754c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
